module.exports = {
	"logo": require('./menu.png'),			
	"info": require('./info-dark.png'),	
	"back": require('./chevron-left-dark.png'),
	"config": require('./gear-dark.png'),
	
	"acediamonds": require('./101.png'),
	"duecediamonds": require('./102.png'),	
	"treydiamonds": require('./103.png'),	
	"fourdiamonds": require('./104.png'),	
	"fivediamonds": require('./105.png'),	
	"sixdiamonds": require('./106.png'),	
	"sevendiamonds": require('./107.png'),	
	"eightdiamonds": require('./108.png'),	
	"ninediamonds": require('./109.png'),	
	"tendiamonds": require('./110.png'),	
	"jackdiamonds": require('./111.png'),	
	"queendiamonds": require('./112.png'),	
	"kingdiamonds": require('./113.png'),	

	"aceclubs": require('./114.png'),
	"duececlubs": require('./115.png'),	
	"treyclubs": require('./116.png'),	
	"fourclubs": require('./117.png'),	
	"fiveclubs": require('./118.png'),	
	"sixclubs": require('./119.png'),	
	"sevenclubs": require('./120.png'),	
	"eightclubs": require('./121.png'),	
	"nineclubs": require('./122.png'),	
	"tenclubs": require('./123.png'),	
	"jackclubs": require('./124.png'),	
	"queenclubs": require('./125.png'),	
	"kingclubs": require('./126.png'),	

	"acehearts": require('./127.png'),
	"duecehearts": require('./128.png'),	
	"treyhearts": require('./129.png'),	
	"fourhearts": require('./130.png'),	
	"fivehearts": require('./131.png'),	
	"sixhearts": require('./132.png'),	
	"sevenhearts": require('./133.png'),	
	"eighthearts": require('./134.png'),	
	"ninehearts": require('./135.png'),	
	"tenhearts": require('./136.png'),	
	"jackhearts": require('./137.png'),	
	"queenhearts": require('./138.png'),	
	"kinghearts": require('./139.png'),	

	"acespades": require('./140.png'),
	"duecespades": require('./141.png'),	
	"treyspades": require('./142.png'),	
	"fourspades": require('./143.png'),	
	"fivespades": require('./144.png'),	
	"sixspades": require('./145.png'),	
	"sevenspades": require('./146.png'),	
	"eightspades": require('./147.png'),	
	"ninespades": require('./148.png'),	
	"tenspades": require('./149.png'),	
	"jackspades": require('./150.png'),	
	"queenspades": require('./151.png'),	
	"kingspades": require('./152.png'),	

	"joker": require('./154.png'),	
	
	"deck": require('./155.png'),	
	"empty": require('./empty.png'),
	"blank": require('./blank.png'),
	"draw": require('./draw-dark.png'),
	"shuffle": require('./shuffle-dark.png'),
	"cardtable": require('./table1.jpg'),
	"dicetable": require('./table4.jpg'),
	"diceroll": require('./dicecup.png')
};
