module.exports = {
	"logo": require('./menu.png'),			
	"info": require('./info-dark.png'),	
	"back": require('./chevron-left-dark.png'),
	"config": require('./gear-dark.png'),
	"reset": require('./reset.png'),
	
	"acediamonds": require('./101.png'),
	"duecediamonds": require('./102.png'),	
	"treydiamonds": require('./103.png'),	
	"fourdiamonds": require('./104.png'),	
	"fivediamonds": require('./105.png'),	
	"sixdiamonds": require('./106.png'),	
	"sevendiamonds": require('./107.png'),	
	"eightdiamonds": require('./108.png'),	
	"ninediamonds": require('./109.png'),	
	"tendiamonds": require('./110.png'),	
	"jackdiamonds": require('./111.png'),	
	"queendiamonds": require('./112.png'),	
	"kingdiamonds": require('./113.png'),	

	"aceclubs": require('./114.png'),
	"duececlubs": require('./115.png'),	
	"treyclubs": require('./116.png'),	
	"fourclubs": require('./117.png'),	
	"fiveclubs": require('./118.png'),	
	"sixclubs": require('./119.png'),	
	"sevenclubs": require('./120.png'),	
	"eightclubs": require('./121.png'),	
	"nineclubs": require('./122.png'),	
	"tenclubs": require('./123.png'),	
	"jackclubs": require('./124.png'),	
	"queenclubs": require('./125.png'),	
	"kingclubs": require('./126.png'),	

	"acehearts": require('./127.png'),
	"duecehearts": require('./128.png'),	
	"treyhearts": require('./129.png'),	
	"fourhearts": require('./130.png'),	
	"fivehearts": require('./131.png'),	
	"sixhearts": require('./132.png'),	
	"sevenhearts": require('./133.png'),	
	"eighthearts": require('./134.png'),	
	"ninehearts": require('./135.png'),	
	"tenhearts": require('./136.png'),	
	"jackhearts": require('./137.png'),	
	"queenhearts": require('./138.png'),	
	"kinghearts": require('./139.png'),	

	"acespades": require('./140.png'),
	"duecespades": require('./141.png'),	
	"treyspades": require('./142.png'),	
	"fourspades": require('./143.png'),	
	"fivespades": require('./144.png'),	
	"sixspades": require('./145.png'),	
	"sevenspades": require('./146.png'),	
	"eightspades": require('./147.png'),	
	"ninespades": require('./148.png'),	
	"tenspades": require('./149.png'),	
	"jackspades": require('./150.png'),	
	"queenspades": require('./151.png'),	
	"kingspades": require('./152.png'),	

	"joker": require('./154.png'),	
	"joker-red": require('./153.png'),	
	"joker-black": require('./154.png'),	

	"hearts": require('./hearts.png'),
	"diamonds": require('./diamonds.png'),
	"clubs": require('./clubs.png'),
	"spades": require('./spades.png'),
	
	"deck": require('./155.png'),	
	"empty": require('./empty.png'),
	"blank": require('./blank.png'),
	"draw": require('./draw-dark.png'),
	"shuffle": require('./shuffle-dark.png'),
	"cardtable": require('./table1.jpg'),
	"dicetable": require('./table4.jpg'),
	"diceroll": require('./dicecup.png'),
	
	"calc": require('./calc.png'),
	"calc-bksp": require('./calc-backspace.png'),
	"calc-add": require('./calc-add.png'),
	"calc-subtract": require('./calc-subtract.png'),
	"calc-multiply": require('./calc-multiply.png'),
	"calc-divide": require('./calc-divide.png'),
	"calc-plus-minus": require('./calc-plus-minus.png'),
	"calc-point": require('./calc-point.png'),
	"calc-equals": require('./calc-equals.png'),
	"calc-clear": require('./calc-clear.png'),
	"calc-att": require('./calc-att.png'),
	"calc-def": require('./calc-def.png'),
	"calc-0": require('./calc-0.png'),
	"calc-1": require('./calc-1.png'),
	"calc-2": require('./calc-2.png'),
	"calc-3": require('./calc-3.png'),
	"calc-4": require('./calc-4.png'),
	"calc-5": require('./calc-5.png'),
	"calc-6": require('./calc-6.png'),
	"calc-7": require('./calc-7.png'),
	"calc-8": require('./calc-8.png'),
	"calc-9": require('./calc-9.png'),

	"support-die-blank": require('./support-die-blank.png'),
	"support-die-air": require('./support-die-air.png'),
	"support-die-armor": require('./support-die-armor.png'),
	"support-die-cas": require('./support-die-cas.png'),
	"support-die-strike": require('./support-die-strike.png'),


	"chevron-left-dark": require('./chevron-left-dark.png'),
	"chevron-right-dark": require('./chevron-right-dark.png'),	
	"chevron-left-light": require('./chevron-left-light.png'),
	"chevron-right-light": require('./chevron-right-light.png'),
	
	"button-plus": require('./button-plus.png'),
	"button-minus": require('./button-minus.png'),

	"add": require('./add.png'),
	"remove": require('./remove.png'),
	"on": require('./abc_btn_radio_to_on_mtrl_015.png'),
	"off": require('./abc_btn_radio_to_on_mtrl_000.png'),
	"unchecked": require('./abc_btn_check_to_on_mtrl_000.png'),//check-checked.png'),
	"checked": require('./abc_btn_check_to_on_mtrl_015.png')//check-unchecked.png')	
};
