module.exports = {
    TOAST: 'TOAST',

    SET_DICE_CONFIG: 'SET_DICE_CONFIG',
    SET_DICE_CONFIG_ENABLED: 'SET_DICE_CONFIG_ENABLED',
    SET_DICE_CONFIG_SIDES: 'SET_DICE_CONFIG_SIDES',
    SET_DICE_CONFIG_NUM: 'SET_DICE_CONFIG_NUM',

    SET_CARD_CONFIG: 'SET_CARD_CONFIG',
    SET_CARD_CONFIG_ENABLED: 'SET_CARD_CONFIG_ENABLED',
    SET_CARD_CONFIG_JOKER: 'SET_CARD_CONFIG_JOKER'
};
