module.exports = {
    TOAST: 'TOAST',

    SET_DICE_CONFIG_ENABLED: 'SET_DICE_CONFIG_ENABLED',
    SET_DICE_CONFIG_DICE: 'SET_DICE_CONFIG_DICE',    

    SET_SPIN_CONFIG_ENABLED: 'SET_SPIN_CONFIG_ENABLED',
    SET_SPIN_CONFIG_NUMBER: 'SET_SPIN_CONFIG_NUMBER',
    SET_SPIN_CONFIG_VALUES: 'SET_SPIN_CONFIG_VALUES',
    SET_SPIN_CONFIG_FOLLOWDICE: 'SET_SPIN_CONFIG_FOLLOWDICE',
    
    SET_CARD_CONFIG_ENABLED: 'SET_CARD_CONFIG_ENABLED',
    SET_CARD_CONFIG_JOKER: 'SET_CARD_CONFIG_JOKER',
    SET_CARD_CONFIG_DECK: 'SET_CARD_CONFIG_DECK',
    SET_CARD_CONFIG_CARD: 'SET_CARD_CONFIG_CARD',
    SET_CARD_CONFIG_DECK_AND_CARD: 'SET_CARD_CONFIG_DECK_AND_CARD'    
};
