module.exports = {
    TOAST: 'TOAST',

    SET_DICE_CONFIG: 'SET_DICE_CONFIG',
    SET_DICE_CONFIG_ENABLED: 'SET_DICE_CONFIG_ENABLED',
    SET_DICE_CONFIG_SIDES: 'SET_DICE_CONFIG_DICE',    

    SET_CARD_CONFIG: 'SET_CARD_CONFIG',
    SET_CARD_CONFIG_ENABLED: 'SET_CARD_CONFIG_ENABLED',
    SET_CARD_CONFIG_JOKER: 'SET_CARD_CONFIG_JOKER',
    SET_CARD_CONFIG_DECK: 'SET_CARD_CONFIG_DECK',
    SET_CARD_CONFIG_CARD: 'SET_CARD_CONFIG_CARD',
    SET_CARD_CONFIG_DECK_AND_CARD: 'SET_CARD_CONFIG_DECK_AND_CARD'    
};
